import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import { Appbar } from "./components/Appbar/Appbar";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ThemeProvider } from "./components/theme-provider";
import RouteAnimation from "./components/RouterAnimations/animations";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        overflow: 'hidden', // This will disable scrolling
      }}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system">
            <Appbar />
            <RouteAnimation>
              {children}
            </RouteAnimation>
            <ToastContainer />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
